[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "brain_tumor_classifier"
version = "0.1.0"
authors = [{name = "autor1", email = "correo@correo.com"}]
description = "Descripción del proyecto"
requires-python = ">3.8"
dependencies = [
    "numpy"
]

[tool.setuptools.packages.find]
where = ["src/"]
